services:
  db:
    container_name: "mysql"
    image: mysql:8.0

    ports:
      - "3306:3306"

    volumes:
      - "./conf.d:/etc/mysql/conf.d"
      - "./data:/var/lib/mysql"

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      # - --default-authentication-plugin=mysql_native_password # When high compatibility with MySQL clients is required

    env_file:
      - .env
